CREATE TYPE SESSION_MODE AS ENUM ('MAIN', 'START');
CREATE TYPE CURRENCY AS ENUM ('ROUBLE', 'DOLLAR', 'EURO', 'HRYVNA', 'TUGHRIK');

CREATE TABLE sessions
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    balance INT NOT NULL CHECK(balance >= 0) DEFAULT 0,
    currency CURRENCY NOT NULL DEFAULT 'ROUBLE',
    mode SESSION_MODE NOT NULL DEFAULT 'MAIN',
    is_on BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMPTZ DEFAULT NOW()
);